### ISSUE TITLE
Implémenter Gh Action pour builder le SDK (Java 17)

### ISSUE THREAD

**Issue by adriens** [opt-nc/colisnc-sdk#2]
# Actions

- [x]  Vérifier que le SDK est bien fonctionnel et que les TUs passent bien (changement éventuel de layout côté web)
- [x] Activer l'action avec les TUs
- [x] Poser le [badge de build (des Gh Actions)](https://docs.github.com/en/actions/managing-workflow-runs/adding-a-workflow-status-badge) sur le README
- [x] Protéger `main` avec la Ci (demander à `Admin` du projet)
- [x] Builder avec la [Build Matrix](https://ncorti.com/blog/howto-github-actions-build-matrix) pour Java `8`, `11` et `17` **Ubuntu et pour windows**  cf exemple de code ci-dessous (on ne fera pas `macos-latest`)
- [x] Activer les nightly build afin d'être courant d'un changement inopportun du layout de la [page web](https://webtracking-nca.ptc.post/)

# Code snippet

```yaml
jobs:
  gradle:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        jdk: [8, 11, 14]
    runs-on: ${{ matrix.os }}
    env:
      JDK_VERSION:  ${{ matrix.jdk }}

  steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    ...
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.jdk }}
```
